defaults:
  - _self_
  - model: resnet50_3d
  - scheduler: multi_step
  - override hydra/launcher: basic

common:
  fp16: true
  seed: 34
  fps: 29.97

dataset:
  frame_based: true
  # path: /home/atuin/b105dc/data/datasets/ellen_show_datasets/ellen_show_length_1300_iou_thr_0.55_video_and_audio
  path: /home/atuin/b105dc/data/datasets/ellen_show_datasets/full_dataset_30_videos_yao_and_suwei/30_videos
  preprocessing:
    subsample_rate: 1
  snippet_len: 10
  csv_home: /home/titan/sles/sles000h/input_files_ellen_with_csv
  split_path: /home/atuin/b105dc/data/datasets/ellen_show_datasets/split.json

training:
  epochs: 220
  batch_size: 8
  train_steps: 1024
  val_steps: 256

criterion:
  name: bce

optimiser:
  name: Adam
  learning_rate: 1e-4
  weight_decay: 1e-5

distributed_training:
  nodes: 1
  gpus: 1
  num_workers: 16
  accumulate_batches: 1

features:
  use_keypoints: false

checkpoints:
  save_top_k: 1

logging:
  log_folder: "/home/atuin/b105dc/data/work/iburenko/logs/resnet50_3d/"
  log_prefix: "${now:%d_%m_%Y}_${now:%H.%M.%S}"
  log_name: "${model.architecture}_${criterion.name}_bs_${training.batch_size}"
  full_path: "${logging.log_folder}${logging.log_prefix}_${logging.log_name}"

augmentations:
  target_size: 112

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - optimiser
  run:
    dir: "${logging.full_path}/tensorboard/"
  sweep:
    dir: "${logging.full_path}/logs/"
    subdir: "${hydra.job.num}_${hydra.job.override_dirname}"
  # launcher:
    # timeout_min: 600
    # nodes: 1
    # gres: "gpu:a100:${distributed_training.gpus}"
    # submitit_folder: "${logging.full_path}/submitit_logs/"
    # tasks_per_node: ${distributed_training.gpus}
    # name: "resnet50_3d_${hydra.job.name}"